//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExammanagefinalEntities : DbContext
    {
        public ExammanagefinalEntities()
            : base("name=ExammanagefinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminlogin> Adminlogins { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<StudentAnswer> StudentAnswers { get; set; }
        public virtual DbSet<Studentdetail> Studentdetails { get; set; }
        public virtual DbSet<StudentExamApplication> StudentExamApplications { get; set; }
        public virtual DbSet<StudentMark> StudentMarks { get; set; }
    }
}
